name: Deploy to ECR

on:
 
  push:
    branches: [ main ]

jobs:
  
  build:
    
    name: Build Image
    runs-on: ubuntu-latest

   
    steps:

    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: AKIAQXDKJAA74A6Z5U
        aws-secret-access-key: xYKcVTzSNKskuQ6CQAAajiRIOmPfInZY1SrZK2PB
        aws-region: us-east-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: saikrishna
        IMAGE_TAG: v2
      run: |
        docker build -t saikrishna .
        docker tag saikrishna:latest public.ecr.aws/v9w6w1e9/saikrishna:latest
        docker push public.ecr.aws/v9w6w1e9/saikrishna:v2
